// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewSsid struct {
	Content string `json:"Content"`
}

type Ssid struct {
	ID      int    `json:"ID"`
	Content string `json:"Content"`
	Anchor  string `json:"Anchor"`
}
