// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterList struct {
	Filters              []*Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FilterList) Reset()         { *m = FilterList{} }
func (m *FilterList) String() string { return proto.CompactTextString(m) }
func (*FilterList) ProtoMessage()    {}
func (*FilterList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{0}
}

func (m *FilterList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterList.Unmarshal(m, b)
}
func (m *FilterList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterList.Marshal(b, m, deterministic)
}
func (m *FilterList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterList.Merge(m, src)
}
func (m *FilterList) XXX_Size() int {
	return xxx_messageInfo_FilterList.Size(m)
}
func (m *FilterList) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterList.DiscardUnknown(m)
}

var xxx_messageInfo_FilterList proto.InternalMessageInfo

func (m *FilterList) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

type Filter struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{1}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Filter) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FilterList)(nil), "pb.FilterList")
	proto.RegisterType((*Filter)(nil), "pb.Filter")
	proto.RegisterType((*Request)(nil), "pb.Request")
}

func init() { proto.RegisterFile("template.proto", fileDescriptor_b1b68e1b5f001c74) }

var fileDescriptor_b1b68e1b5f001c74 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0xcd, 0x2d,
	0xc8, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x92,
	0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f,
	0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x50, 0x32, 0xe2, 0xe2, 0x72, 0xcb, 0xcc, 0x29,
	0x49, 0x2d, 0xf2, 0xc9, 0x2c, 0x2e, 0x11, 0x52, 0xe1, 0x62, 0x4f, 0x03, 0xf3, 0x8a, 0x25, 0x18,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0xb8, 0xf4, 0x0a, 0x92, 0xf4, 0x20, 0x0a, 0x82, 0x60, 0x52, 0x4a,
	0x16, 0x5c, 0x6c, 0x10, 0x21, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0x37, 0x37, 0x35,
	0xaf, 0x44, 0x82, 0x09, 0x2c, 0x0e, 0xe3, 0x2a, 0x71, 0x72, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x18, 0x85, 0x71, 0x71, 0x47, 0xe6, 0x97, 0x16, 0x05, 0xa7, 0x16, 0x95, 0x65, 0x26,
	0xa7, 0x0a, 0xb9, 0x73, 0xf1, 0xba, 0xa7, 0x96, 0x20, 0x39, 0x85, 0x1b, 0x64, 0x33, 0x54, 0xb1,
	0x14, 0x1f, 0xc2, 0x19, 0x20, 0x49, 0x25, 0xc9, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0x09, 0x2b, 0xf1,
	0xe9, 0x97, 0x19, 0xea, 0xa7, 0xc1, 0xc5, 0xad, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0xfe, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x6c, 0x46, 0x2c, 0x0b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// YourServiceClient is the client API for YourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YourServiceClient interface {
	GetFilterList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*FilterList, error)
}

type yourServiceClient struct {
	cc *grpc.ClientConn
}

func NewYourServiceClient(cc *grpc.ClientConn) YourServiceClient {
	return &yourServiceClient{cc}
}

func (c *yourServiceClient) GetFilterList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*FilterList, error) {
	out := new(FilterList)
	err := c.cc.Invoke(ctx, "/pb.YourService/GetFilterList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YourServiceServer is the server API for YourService service.
type YourServiceServer interface {
	GetFilterList(context.Context, *Request) (*FilterList, error)
}

// UnimplementedYourServiceServer can be embedded to have forward compatible implementations.
type UnimplementedYourServiceServer struct {
}

func (*UnimplementedYourServiceServer) GetFilterList(ctx context.Context, req *Request) (*FilterList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilterList not implemented")
}

func RegisterYourServiceServer(s *grpc.Server, srv YourServiceServer) {
	s.RegisterService(&_YourService_serviceDesc, srv)
}

func _YourService_GetFilterList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YourServiceServer).GetFilterList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YourService/GetFilterList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YourServiceServer).GetFilterList(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _YourService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.YourService",
	HandlerType: (*YourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilterList",
			Handler:    _YourService_GetFilterList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}
